/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PublicoRouteImport } from './routes/publico'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAsignacionesRouteImport } from './routes/_authenticated/asignaciones'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedBrunoRouteImport } from './routes/_authenticated/bruno'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedEjecucionesRouteImport } from './routes/_authenticated/ejecuciones'
import { Route as AuthenticatedGreenGateRouteImport } from './routes/_authenticated/green-gate'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMelaniaRouteImport } from './routes/_authenticated/melania'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMetricsRouteImport } from './routes/_authenticated/metrics'
import { Route as AuthenticatedOperadorRouteImport } from './routes/_authenticated/operador'
import { Route as AuthenticatedOperadorDashboardRouteImport } from './routes/_authenticated/operador-dashboard'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'
import { Route as AuthenticatedLuxiaStageRouteImport } from './routes/_authenticated/luxia.$stage'
import { Route as AuthenticatedMeetingsIndexRouteImport } from './routes/_authenticated/meetings.index'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings.$meetingId'
import { Route as ApiPublicCronDailyMeetingRouteImport } from './routes/api/public/cron/daily-meeting'
import { Route as ApiPublicN8nCallbackRouteImport } from './routes/api/public/n8n/callback'
import { Route as ApiPublicN8nDispatchRouteImport } from './routes/api/public/n8n/dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoRoute = PublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsignacionesRoute =
  AuthenticatedAsignacionesRouteImport.update({
    id: '/asignaciones',
    path: '/asignaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrunoRoute = AuthenticatedBrunoRouteImport.update({
  id: '/bruno',
  path: '/bruno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEjecucionesRoute =
  AuthenticatedEjecucionesRouteImport.update({
    id: '/ejecuciones',
    path: '/ejecuciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGreenGateRoute = AuthenticatedGreenGateRouteImport.update({
  id: '/green-gate',
  path: '/green-gate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMelaniaRoute = AuthenticatedMelaniaRouteImport.update({
  id: '/melania',
  path: '/melania',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricsRoute = AuthenticatedMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperadorRoute = AuthenticatedOperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperadorDashboardRoute =
  AuthenticatedOperadorDashboardRouteImport.update({
    id: '/operador-dashboard',
    path: '/operador-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const AuthenticatedLuxiaStageRoute = AuthenticatedLuxiaStageRouteImport.update({
  id: '/luxia/$stage',
  path: '/luxia/$stage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsIndexRoute =
  AuthenticatedMeetingsIndexRouteImport.update({
    id: '/meetings/',
    path: '/meetings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/meetings/$meetingId',
    path: '/meetings/$meetingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronDailyMeetingRoute =
  ApiPublicCronDailyMeetingRouteImport.update({
    id: '/api/public/cron/daily-meeting',
    path: '/api/public/cron/daily-meeting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nCallbackRoute = ApiPublicN8nCallbackRouteImport.update({
  id: '/api/public/n8n/callback',
  path: '/api/public/n8n/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nDispatchRoute = ApiPublicN8nDispatchRouteImport.update({
  id: '/api/public/n8n/dispatch',
  path: '/api/public/n8n/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/publico': typeof PublicoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/bruno': typeof AuthenticatedBrunoRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/command': typeof AuthenticatedCommandRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/ejecuciones': typeof AuthenticatedEjecucionesRoute
  '/green-gate': typeof AuthenticatedGreenGateRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/melania': typeof AuthenticatedMelaniaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/operador': typeof AuthenticatedOperadorRoute
  '/operador-dashboard': typeof AuthenticatedOperadorDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/luxia/$stage': typeof AuthenticatedLuxiaStageRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/api/public/cron/daily-meeting': typeof ApiPublicCronDailyMeetingRoute
  '/api/public/n8n/callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/publico': typeof PublicoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/bruno': typeof AuthenticatedBrunoRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/command': typeof AuthenticatedCommandRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/ejecuciones': typeof AuthenticatedEjecucionesRoute
  '/green-gate': typeof AuthenticatedGreenGateRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/melania': typeof AuthenticatedMelaniaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/operador': typeof AuthenticatedOperadorRoute
  '/operador-dashboard': typeof AuthenticatedOperadorDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/luxia/$stage': typeof AuthenticatedLuxiaStageRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/meetings': typeof AuthenticatedMeetingsIndexRoute
  '/api/public/cron/daily-meeting': typeof ApiPublicCronDailyMeetingRoute
  '/api/public/n8n/callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/publico': typeof PublicoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/bruno': typeof AuthenticatedBrunoRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/ejecuciones': typeof AuthenticatedEjecucionesRoute
  '/_authenticated/green-gate': typeof AuthenticatedGreenGateRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/melania': typeof AuthenticatedMelaniaRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/metrics': typeof AuthenticatedMetricsRoute
  '/_authenticated/operador': typeof AuthenticatedOperadorRoute
  '/_authenticated/operador-dashboard': typeof AuthenticatedOperadorDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/luxia/$stage': typeof AuthenticatedLuxiaStageRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/_authenticated/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/api/public/cron/daily-meeting': typeof ApiPublicCronDailyMeetingRoute
  '/api/public/n8n/callback': typeof ApiPublicN8nCallbackRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/publico'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/approvals'
    | '/asignaciones'
    | '/automations'
    | '/bruno'
    | '/ceo'
    | '/clientes'
    | '/command'
    | '/dashboards'
    | '/decisions'
    | '/ejecuciones'
    | '/green-gate'
    | '/leads'
    | '/melania'
    | '/metas'
    | '/metrics'
    | '/operador'
    | '/operador-dashboard'
    | '/products'
    | '/revenue'
    | '/settings'
    | '/tasks'
    | '/today'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agents/$agentId'
    | '/luxia/$stage'
    | '/meetings/$meetingId'
    | '/meetings/'
    | '/api/public/cron/daily-meeting'
    | '/api/public/n8n/callback'
    | '/api/public/n8n/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/publico'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activity'
    | '/admin'
    | '/agents'
    | '/approvals'
    | '/asignaciones'
    | '/automations'
    | '/bruno'
    | '/ceo'
    | '/clientes'
    | '/command'
    | '/dashboards'
    | '/decisions'
    | '/ejecuciones'
    | '/green-gate'
    | '/leads'
    | '/melania'
    | '/metas'
    | '/metrics'
    | '/operador'
    | '/operador-dashboard'
    | '/products'
    | '/revenue'
    | '/settings'
    | '/tasks'
    | '/today'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agents/$agentId'
    | '/luxia/$stage'
    | '/meetings/$meetingId'
    | '/meetings'
    | '/api/public/cron/daily-meeting'
    | '/api/public/n8n/callback'
    | '/api/public/n8n/dispatch'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/publico'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/agents'
    | '/_authenticated/approvals'
    | '/_authenticated/asignaciones'
    | '/_authenticated/automations'
    | '/_authenticated/bruno'
    | '/_authenticated/ceo'
    | '/_authenticated/clientes'
    | '/_authenticated/command'
    | '/_authenticated/dashboards'
    | '/_authenticated/decisions'
    | '/_authenticated/ejecuciones'
    | '/_authenticated/green-gate'
    | '/_authenticated/leads'
    | '/_authenticated/melania'
    | '/_authenticated/metas'
    | '/_authenticated/metrics'
    | '/_authenticated/operador'
    | '/_authenticated/operador-dashboard'
    | '/_authenticated/products'
    | '/_authenticated/revenue'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/luxia/$stage'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/meetings/'
    | '/api/public/cron/daily-meeting'
    | '/api/public/n8n/callback'
    | '/api/public/n8n/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PublicoRoute: typeof PublicoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCronDailyMeetingRoute: typeof ApiPublicCronDailyMeetingRoute
  ApiPublicN8nCallbackRoute: typeof ApiPublicN8nCallbackRoute
  ApiPublicN8nDispatchRoute: typeof ApiPublicN8nDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico': {
      id: '/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof PublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asignaciones': {
      id: '/_authenticated/asignaciones'
      path: '/asignaciones'
      fullPath: '/asignaciones'
      preLoaderRoute: typeof AuthenticatedAsignacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bruno': {
      id: '/_authenticated/bruno'
      path: '/bruno'
      fullPath: '/bruno'
      preLoaderRoute: typeof AuthenticatedBrunoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ejecuciones': {
      id: '/_authenticated/ejecuciones'
      path: '/ejecuciones'
      fullPath: '/ejecuciones'
      preLoaderRoute: typeof AuthenticatedEjecucionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/green-gate': {
      id: '/_authenticated/green-gate'
      path: '/green-gate'
      fullPath: '/green-gate'
      preLoaderRoute: typeof AuthenticatedGreenGateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/melania': {
      id: '/_authenticated/melania'
      path: '/melania'
      fullPath: '/melania'
      preLoaderRoute: typeof AuthenticatedMelaniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metrics': {
      id: '/_authenticated/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthenticatedMetricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operador': {
      id: '/_authenticated/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof AuthenticatedOperadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operador-dashboard': {
      id: '/_authenticated/operador-dashboard'
      path: '/operador-dashboard'
      fullPath: '/operador-dashboard'
      preLoaderRoute: typeof AuthenticatedOperadorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/_authenticated/luxia/$stage': {
      id: '/_authenticated/luxia/$stage'
      path: '/luxia/$stage'
      fullPath: '/luxia/$stage'
      preLoaderRoute: typeof AuthenticatedLuxiaStageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings/': {
      id: '/_authenticated/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthenticatedMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/daily-meeting': {
      id: '/api/public/cron/daily-meeting'
      path: '/api/public/cron/daily-meeting'
      fullPath: '/api/public/cron/daily-meeting'
      preLoaderRoute: typeof ApiPublicCronDailyMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/callback': {
      id: '/api/public/n8n/callback'
      path: '/api/public/n8n/callback'
      fullPath: '/api/public/n8n/callback'
      preLoaderRoute: typeof ApiPublicN8nCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/dispatch': {
      id: '/api/public/n8n/dispatch'
      path: '/api/public/n8n/dispatch'
      fullPath: '/api/public/n8n/dispatch'
      preLoaderRoute: typeof ApiPublicN8nDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAsignacionesRoute: typeof AuthenticatedAsignacionesRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBrunoRoute: typeof AuthenticatedBrunoRoute
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedEjecucionesRoute: typeof AuthenticatedEjecucionesRoute
  AuthenticatedGreenGateRoute: typeof AuthenticatedGreenGateRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMelaniaRoute: typeof AuthenticatedMelaniaRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMetricsRoute: typeof AuthenticatedMetricsRoute
  AuthenticatedOperadorRoute: typeof AuthenticatedOperadorRoute
  AuthenticatedOperadorDashboardRoute: typeof AuthenticatedOperadorDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedLuxiaStageRoute: typeof AuthenticatedLuxiaStageRoute
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRoute
  AuthenticatedMeetingsIndexRoute: typeof AuthenticatedMeetingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAsignacionesRoute: AuthenticatedAsignacionesRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBrunoRoute: AuthenticatedBrunoRoute,
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedEjecucionesRoute: AuthenticatedEjecucionesRoute,
  AuthenticatedGreenGateRoute: AuthenticatedGreenGateRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMelaniaRoute: AuthenticatedMelaniaRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMetricsRoute: AuthenticatedMetricsRoute,
  AuthenticatedOperadorRoute: AuthenticatedOperadorRoute,
  AuthenticatedOperadorDashboardRoute: AuthenticatedOperadorDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedLuxiaStageRoute: AuthenticatedLuxiaStageRoute,
  AuthenticatedMeetingsMeetingIdRoute: AuthenticatedMeetingsMeetingIdRoute,
  AuthenticatedMeetingsIndexRoute: AuthenticatedMeetingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PublicoRoute: PublicoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCronDailyMeetingRoute: ApiPublicCronDailyMeetingRoute,
  ApiPublicN8nCallbackRoute: ApiPublicN8nCallbackRoute,
  ApiPublicN8nDispatchRoute: ApiPublicN8nDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
